# Generated by Django 4.0.3 on 2022-03-08 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.CharField(default=projects.models.idgen, max_length=20, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=20)),
                ('projectSize', models.IntegerField(default=25)),
                ('projectAccounts', models.ManyToManyField(related_name='accounts', to='accounts.account')),
                ('projectGuests', models.ManyToManyField(related_name='guests', to=settings.AUTH_USER_MODEL)),
                ('projectOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
