# Generated by Django 4.0.3 on 2022-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='comments',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='media',
            name='likes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='media',
            name='views',
            field=models.JSONField(default=dict),
        ),
    ]
