# Generated by Django 4.0.3 on 2022-03-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_media_comments_alter_media_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='accounts.account'),
        ),
    ]
