# Generated by Django 4.0.3 on 2022-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_media_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='resources',
            field=models.JSONField(default=dict),
        ),
    ]
