# Generated by Django 4.0.3 on 2022-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_media_rcomments_media_rlikes_media_rviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='rComments',
        ),
        migrations.RemoveField(
            model_name='media',
            name='rLikes',
        ),
        migrations.RemoveField(
            model_name='media',
            name='rViews',
        ),
        migrations.AddField(
            model_name='account',
            name='analyze',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='media',
            name='analyze',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='medias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
